### ISSUE TITLE
error Error while sending email: Error: Can't create new access token for user

### ISSUE THREAD

**Issue by negati-ve** [MattieBelt/strapi-provider-email-gmail-2lo#2]
I've followed the steps and created a service account and have the service account client id and private key in my env too

full error
[2020-11-04T07:59:10.252Z] error Error while sending email: Error: Can't create new access token for user
AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
at Function.boomify (/srv/app/node_modules/boom/lib/index.js:107:14)
at formatBoomPayload (/srv/app/node_modules/strapi/lib/middlewares/boom/index.js:47:22)
at /srv/app/node_modules/strapi/lib/middlewares/boom/index.js:84:36
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by negati-ve** [comment]
Turns out normal gmail accounts cannot be used with service accounts
